#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export FAULTCHECK_PATH=$DIR"/FaultCheck"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FAULTCHECK_PATH

export COPTERSIM_PATH=$DIR"/CopterSim"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$COPTERSIM_PATH

